### ISSUE TITLE
can you please add demo project to use this.?

### ISSUE THREAD

**Issue by cloudjanak** [basdvries/BDVCountryNameAndCode#3]

**Comment by basdvries** [comment]
What are you having trouble with? I don't think a demo project is needed since the usage is just pretty straightforward, but that could be just me.

**Comment by abidullah** [comment]
if its so simple then give a example and help it use in a simple way

**Comment by basdvries** [comment]
What type of example are you looking for? In the readme there's basically most of the functionality explained.

**Comment by abidullah** [comment]
a simple example to search the country name by entering the dialing code

![ios simulator screen shot feb 17 2015 11 27 09 pm](https://cloud.githubusercontent.com/assets/2981996/6235523/8713cfc4-b6fc-11e4-9a58-85c46fe8111c.png)

**Comment by basdvries** [comment]
What you're asking for is actually not something that was not directly supported by this library. However, I just pushed a method that does the exact same thing you're asking for. Please note: this does only return the first 2 letters of the country in an array. Because one prefix can have multiple regions (+1 for example). Hope this helps.

**Comment by abidullah** [comment]
can you just tell me how to use ur library in code please
